---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      logging:

      jaeger:
        endpoint: "jaeger-collector-headless:14250"
        tls:
          insecure: true

    processors:
      batch:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
  annotations:
    configmap.reloader.stakater.com/reload: "otel-collector-config"
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.51.0
          volumeMounts:
            - mountPath: /etc/otelcol-contrib/config.yaml
              name: data
              subPath: config.yaml
              readOnly: true
          ports:
            - name: collector
              containerPort: 4317
              protocol: TCP
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
    - name: collector
      port: 4317
  selector:
    component: otel-collector
